'use client';
import {useEffect,useRef,useState} from 'react';
const key='verra-reading-preferences';
type Preferences={largerText:boolean;reduceMotion:boolean;quietSurfaces:boolean};
const defaults:Preferences={largerText:false,reduceMotion:false,quietSurfaces:false};
function read():Preferences{try{const p=JSON.parse(localStorage.getItem(key)||'{}');return {largerText:p.largerText===true,reduceMotion:p.reduceMotion===true,quietSurfaces:p.quietSurfaces===true};}catch{return defaults;}}
function apply(p:Preferences){const root=document.documentElement;root.dataset.calm=p.largerText&&p.reduceMotion&&p.quietSurfaces?'on':'off';root.dataset.reading=p.largerText?'comfortable':'standard';root.dataset.motion=p.reduceMotion?'reduced':'system';root.dataset.surfaces=p.quietSurfaces?'quiet':'standard';}
export function ComfortControls(){
 const [prefs,setPrefs]=useState(defaults),[notice,setNotice]=useState('');const dialog=useRef<HTMLDialogElement>(null);const opener=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const sync=()=>{const value=read();setPrefs(value);apply(value);};sync();window.addEventListener('verra-reading-change',sync);window.addEventListener('storage',sync);return()=>{window.removeEventListener('verra-reading-change',sync);window.removeEventListener('storage',sync);};},[]);
 function save(next:Preferences){setPrefs(next);apply(next);try{localStorage.setItem(key,JSON.stringify(next));window.dispatchEvent(new Event('verra-reading-change'));setNotice('Reading preferences saved on this device.');}catch{setNotice('Preferences applied for this page. Device storage is unavailable.');}}
 const calm=prefs.largerText&&prefs.reduceMotion&&prefs.quietSurfaces;
 return <div className="comfort-controls"><button className="calm-toggle" aria-pressed={calm} aria-label="Calm mode" onClick={()=>save(calm?defaults:{largerText:true,reduceMotion:true,quietSurfaces:true})}><span aria-hidden="true">◒</span> Calm <span className="calm-state">{calm?'On':'Off'}</span></button><button ref={opener} className="reading-button" aria-label="Reading preferences" onClick={()=>dialog.current?.showModal()}><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16"/><path strokeWidth="4" d="M9 3v6m7 0v6m-7 0v6"/></svg></button><dialog className="comfort-dialog" ref={dialog} aria-labelledby="comfort-title" onClose={()=>opener.current?.focus()} onClick={e=>{if(e.target===dialog.current)dialog.current.close();}}><div className="dialog-heading"><span className="eyebrow">Make yourself comfortable</span><button aria-label="Close reading preferences" onClick={()=>dialog.current?.close()}>×</button></div><h2 id="comfort-title">Less to process.<br/>More room to read.</h2><p>Choose what helps you. Calm mode combines these three settings. It is available to everyone, including people who prefer a lower-sensory experience.</p><div className="comfort-options">{([['largerText','Comfortable text','Larger type, relaxed spacing and simpler interface headings.'],['reduceMotion','Less motion','Stop transitions and animated movement. System reduced-motion preferences are always respected.'],['quietSurfaces','Quiet layout','Soften decorative color blocks, remove shadows and use one reading column in visit details.']] as const).map(([id,title,help])=><label key={id}><span><b>{title}</b><small>{help}</small></span><input type="checkbox" checked={prefs[id]} onChange={e=>save({...prefs,[id]:e.target.checked})}/></label>)}</div><p className="comfort-boundary">Requirements, conflicts, evidence and sharing permissions stay visible and unchanged.</p><p className="comfort-status" role="status">{notice}</p><button className="primary" onClick={()=>dialog.current?.close()}>Done</button></dialog></div>;
}
