'use client';
import {useEffect,useRef,useState} from 'react';
import {readingKey as key,readingDefaults as defaults,normalizeReading,applyReading as apply,type ReadingPreferences as Preferences} from '@/lib/reading-preferences';
import {ReadAloud} from './read-aloud';
function read():Preferences{try{return normalizeReading(JSON.parse(localStorage.getItem(key)||'{}'));}catch{return defaults;}}
export function ComfortControls(){
 const [prefs,setPrefs]=useState(defaults),[notice,setNotice]=useState('');const dialog=useRef<HTMLDialogElement>(null);const opener=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const sync=()=>{const value=read();setPrefs(value);apply(value);};sync();window.addEventListener('verra-reading-change',sync);window.addEventListener('storage',sync);const open=()=>dialog.current?.showModal();window.addEventListener('verra-open-accessibility',open);return()=>{window.removeEventListener('verra-reading-change',sync);window.removeEventListener('storage',sync);window.removeEventListener('verra-open-accessibility',open);};},[]);
 function save(next:Preferences){setPrefs(next);apply(next);try{localStorage.setItem(key,JSON.stringify(next));window.dispatchEvent(new Event('verra-reading-change'));setNotice('Reading preferences saved on this device.');}catch{setNotice('Preferences applied for this page. Device storage is unavailable.');}}
 const calm=prefs.largerText&&prefs.reduceMotion&&prefs.quietSurfaces;
 return <div className="comfort-controls"><button className="calm-toggle" aria-pressed={calm} aria-label="Calm mode" onClick={()=>save({...prefs,largerText:!calm,reduceMotion:!calm,quietSurfaces:!calm})}><span aria-hidden="true">◒</span> Calm <span className="calm-state">{calm?'On':'Off'}</span></button><button ref={opener} className="reading-button" aria-label="Accessibility and reading preferences" onClick={()=>dialog.current?.showModal()}><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16"/><path strokeWidth="4" d="M9 3v6m7 0v6m-7 0v6"/></svg><span className="access-label">Accessibility</span></button><dialog className="comfort-dialog" ref={dialog} aria-labelledby="comfort-title" onClose={()=>opener.current?.focus()} onClick={e=>{if(e.target===dialog.current)dialog.current.close();}}><div className="dialog-heading"><span className="eyebrow">Make yourself comfortable</span><button aria-label="Close reading preferences" onClick={()=>dialog.current?.close()}>×</button></div><h2 id="comfort-title">Make Verra work for you.</h2><p>Choose what helps you. Calm mode combines comfortable text, less motion and a quiet layout. It is available to everyone, including people who prefer a lower-sensory experience.</p><div className="comfort-options">{([['largerText','Comfortable text','Larger type, relaxed spacing and simpler interface headings.'],['reduceMotion','Less motion','Stop transitions and animated movement. System reduced-motion preferences are always respected.'],['quietSurfaces','Quiet layout','Soften decorative color blocks, remove shadows and use one reading column in visit details.'],['strongContrast','Stronger contrast','Clearer text, controls and borders in either theme.'],['colorSupport','Colour-blind support','Distinguish statuses with shapes, words and border patterns, without relying on red or green.'],['underlineLinks','Underline links','Make links easier to recognise without relying on their colour.']] as const).map(([id,title,help])=><label key={id}><span><b>{title}</b><small>{help}</small></span><input type="checkbox" checked={prefs[id]} onChange={e=>save({...prefs,[id]:e.target.checked})}/></label>)}</div><ReadAloud onStart={()=>dialog.current?.close()}/><p className="comfort-boundary">Requirements, conflicts, evidence and sharing permissions stay visible and unchanged.</p><p className="comfort-status" role="status">{notice}</p><button className="primary" onClick={()=>dialog.current?.close()}>Done</button></dialog></div>;
}
