'use client';
import { useEffect, useState, useRef, type ReactNode } from 'react';
import { ComfortControls } from './comfort-controls';
export function Icon({name='arrow',size=20}:{name?:string;size?:number}){
 const paths:Record<string,ReactNode>={
 home:<><path d="m3 10 9-7 9 7v10H3Z"/><path d="M9 20v-7h6v7"/></>,visits:<><rect x="4" y="5" width="16" height="16" rx="3"/><path d="M8 3v4m8-4v4M4 11h16m-12 5h3"/></>,needs:<><path d="M12 20s-8-5-8-11a4 4 0 0 1 8-2 4 4 0 0 1 8 2c0 6-8 11-8 11Z"/></>,message:<><path d="M4 4h16v12H9l-5 4Z"/><path d="M8 8h8m-8 4h5"/></>,check:<path d="m5 12 4 4L19 6"/>,shield:<><path d="m12 3 8 3v6c0 5-8 9-8 9S4 17 4 12V6Z"/><path d="m8 11 3 3 5-5"/></>,arrow:<path d="M5 12h14m-6-6 6 6-6 6"/>,sun:<><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/></>,moon:<path d="M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z"/>,settings:<><circle cx="12" cy="12" r="3"/><path d="m9 3-1 3-3 1v4l-2 1 2 2v4l3 1 1 2h6l1-2 3-1v-4l2-2-2-1V7l-3-1-1-3Z"/></>,book:<><path d="M12 5C8 2 3 4 3 4v16s5-2 9 0c4-2 9 0 9 0V4s-5-2-9 1Zm0 0v15"/></>,plus:<path d="M12 5v14M5 12h14"/>,link:<><path d="m10 8 3-3a4 4 0 0 1 6 6l-3 3m-2 2-3 3a4 4 0 0 1-6-6l3-3m0 6 8-8"/></>,spark:<><path d="M12 3v4m0 10v4M3 12h4m10 0h4"/><circle cx="12" cy="12" r="3"/></>};
 return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]||paths.arrow}</svg>;
}
export function ThemeToggle(){const [dark,setDark]=useState(false);useEffect(()=>setDark(document.documentElement.dataset.theme==='dark'),[]);return <button className="theme-switch" aria-label={dark?'Use light theme':'Use dark theme'} onClick={()=>{const next=!dark;setDark(next);document.documentElement.dataset.theme=next?'dark':'light';try{localStorage.setItem('verra-appearance',next?'dark':'light');}catch{}}}><Icon name={dark?'sun':'moon'}/></button>;}
export function SiteHeader(){const [open,setOpen]=useState(false);return <header className="site-header"><a className="brand" href="/">Verra<span className="brand-period">.</span></a><button className="site-menu-button" aria-expanded={open} onClick={()=>setOpen(!open)}>Menu</button><nav className={open?'site-nav open':'site-nav'} aria-label="Main navigation"><a href="/#experience" onClick={()=>setOpen(false)}>The experience</a><a href="/#how" onClick={()=>setOpen(false)}>How it works</a><a href="/judges">For judges</a></nav><div className="site-actions"><ComfortControls/><ThemeToggle/><a className="sign-in-link" href="/signin">Sign in</a><a className="button primary" href="/demo">Explore the demo <Icon size={16}/></a></div></header>;}
export function SiteFooter(){return <footer className="site-footer"><div><a href="/" className="brand">Verra.</a><p>More room for living.<br/>More care with the details.</p></div><nav aria-label="Footer"><a href="/demo">Explore the demo</a><a href="/judges">Judge’s guide</a><a href="/privacy">Privacy & permissions</a><a href="/signin">Your account</a></nav><p className="footer-note">Built around access needs.<br/>Verra is in active development.</p></footer>;}
export const workspaceLinks=[['overview','home','Overview'],['list','visits','Your visits'],['activity','message','Activity'],['profile','needs','Access needs'],['settings','settings','Settings']] as const;
export function WorkspaceFrame({children,view,onNavigate,demo=false,name='Your workspace',actions}:{children:ReactNode;view:string;onNavigate:(view:string)=>void;demo?:boolean;name?:string;actions?:ReactNode}){
 const menu=useRef<HTMLDialogElement>(null);const menuButton=useRef<HTMLButtonElement>(null);
 const links=demo?[['overview','home','Overview'],['list','visits','Your visits'],['decisions','shield','Decisions'],['profile','needs','Access needs'],['settings','link','Connections'],['guide','book','Judge’s guide']]:workspaceLinks;
 useEffect(()=>{const heading=document.querySelector<HTMLElement>('.workspace-body main h1');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}},[view]);
 return <div className="workspace-frame"><aside className="workspace-sidebar"><a href="/" className="brand">Verra.</a><p className="sidebar-label">{demo?'Explore Verra':'Your space'}</p><nav aria-label="Personal workspace">{links.map(([key,icon,label])=><button key={key} aria-current={view===key?'page':undefined} onClick={()=>onNavigate(key)}><Icon name={icon}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><div className="sidebar-note"><Icon name="shield"/><p>Your needs.<br/>Your permission.</p></div><a href="/privacy">About your data <Icon size={14}/></a><div className="workspace-person"><span className="person-avatar">{demo?'D':name.slice(0,1).toUpperCase()}</span><div><b>{demo?'Demo explorer':name}</b><small>{demo?'Fictional sample visits':'Personal workspace'}</small></div></div></div></aside><div className="workspace-body"><header className="workspace-topbar"><span><a href="/" className="mobile-wordmark">Verra.</a><span className="workspace-crumb">Workspace <span className="breadcrumb-slash">/</span> {view==='detail'?'Visit details':view==='edit'?'Edit visit':view==='new'?'New visit':view==='list'?'Your visits':view==='profile'?'Access needs':view.charAt(0).toUpperCase()+view.slice(1)}</span></span><div><ComfortControls/><ThemeToggle/><span className="desktop-workspace-actions">{actions}</span></div></header>{children}</div><nav className="mobile-bottom-nav" aria-label="Mobile workspace">{links.slice(0,4).map(([key,icon,label])=><button key={key} aria-label={label} aria-current={(view===key||(key==='list'&&['detail','new','edit'].includes(view)))?'page':undefined} onClick={()=>onNavigate(key)}><Icon name={icon} size={22}/><span>{key==='overview'?'Home':key==='list'?'Visits':key==='profile'?'Needs':label}</span></button>)}<button ref={menuButton} aria-haspopup="dialog" aria-label="More workspace options" onClick={()=>menu.current?.showModal()}><span className="more-dots" aria-hidden="true">•••</span><span>More</span></button></nav><dialog ref={menu} className="workspace-menu" aria-labelledby="workspace-menu-title" onClose={()=>menuButton.current?.focus()} onClick={e=>{if(e.target===menu.current)menu.current.close();}}><div className="dialog-heading"><h2 id="workspace-menu-title">Your workspace</h2><button aria-label="Close workspace menu" onClick={()=>menu.current?.close()}>×</button></div><p>Everything else, close at hand.</p><nav aria-label="More workspace options">{links.slice(4).map(([key,icon,label])=><button key={key} onClick={()=>{menu.current?.close();onNavigate(key);}}><Icon name={icon}/>{label}<Icon size={15}/></button>)}<a href="/privacy"><Icon name="shield"/>Privacy & permissions</a><a href="/"><Icon name="home"/>Back to website</a></nav><div className="menu-session-actions">{actions}</div><button className="primary" onClick={()=>menu.current?.close()}>Back to my visit</button></dialog></div>;
}
