import type {SampleVisit} from './demo-model';
export type CompanionAnswer={text:string;action:{label:string;tab:'requirements'|'evidence'|'messages'|'plan'}};
export const companionQuestions=['What still needs an answer?','What would Verra ask?','What can I try next?'];
export function answerDemoQuestion(question:string,visit:SampleVisit):CompanionAnswer{
 const q=question.toLowerCase();
 if(/share|privacy|permission|private/.test(q))return {text:`For ${visit.venue}, ${visit.shared.filter(Boolean).length} of ${visit.needs.length} needs are marked for sharing. ${visit.stage==='cancelled'?'Cancellation has revoked sharing.':'Review each checkbox before approving a question. Keeping a need private does not remove it from your requirements.'}`,action:{label:'Review sharing choices',tab:'requirements'}};
 if(/what would|ask|question|proposal|alternative/.test(q))return {text:visit.stage==='cancelled'?'This visit is cancelled. Its previous proposal is kept as history, and cannot advance.':`${visit.proposal} ${visit.shared.slice(0,Math.min(2,visit.needs.length)).every(Boolean)?'You can review the proposal before deciding.':'Sharing for the required needs must be allowed before approval.'}`,action:{label:'Review the proposal',tab:'requirements'}};
 if(/next|try|how|start|help|pause|cancel/.test(q))return {text:visit.stage==='cancelled'?'This visit is cancelled. Explore a different visit, or reset the demo to try the sequence again.':visit.paused?'This visit is paused. Resume from the next-step panel when you want to continue. Your needs are unchanged.':visit.stage==='plan'?'Open the visit plan and look at the remaining uncertainty. Supporting evidence for two needs does not confirm every detail.':visit.stage==='waiting'?visit.id.startsWith('sample-')?'This custom visit has no prepared reply. Use a starting scenario to explore how a reply changes the plan.':'Your question is approved in the demo. Load the example venue reply from the next-step panel, then review the updated plan.':'Start with the evidence, then review the proposed question. You can approve, decline, pause or change the sharing choices.',action:{label:visit.stage==='plan'?'Open visit plan':'Show the next step',tab:visit.stage==='plan'?'plan':'requirements'}};
 if(/need|answer|safe|access|attend|confirm|room|lift|quiet|source|evidence|why|ready/.test(q))return {text:visit.stage==='draft'?'This visit has no gathered evidence. Its requirements remain unanswered. Start with a clear question for each need.':visit.stage==='plan'?`${visit.resolution} ${visit.needs.length>2?`Still unanswered: ${visit.needs.slice(2).join('; ')}.`:''} This is evidence within the example, not a guarantee for a real visit.`:`${visit.issue} The requirement stays: ${visit.needs[0]}. Compare the website statement with the room-specific reply before deciding.`,action:{label:'Compare the evidence',tab:'evidence'}};
 return {text:`I can help you explore ${visit.title}: its evidence, unanswered needs, sharing choices and next step. Try “What still needs an answer?” or “What would Verra ask?”`,action:{label:'Open this visit',tab:'requirements'}};
}
