import { z } from 'zod';
export const sampleVisitSchema=z.object({id:z.string().max(80),title:z.string().min(1).max(160),venue:z.string().min(1).max(160),category:z.string().max(60),date:z.string().max(60),needs:z.array(z.string().min(1).max(1000)).min(1).max(30),issue:z.string().max(1500),proposal:z.string().max(1500),website:z.string().max(1500),reply:z.string().max(1500),resolution:z.string().max(1500),arrival:z.string().max(1500),stage:z.enum(['draft','review','waiting','plan','declined','cancelled']),paused:z.boolean(),shared:z.array(z.boolean()).max(30),history:z.array(z.string().max(200)).max(100)});
export const demoStateSchema=z.object({visits:z.array(sampleVisitSchema).min(1).max(30),needs:z.array(z.string().min(3).max(1000)).max(30)});
export type SampleVisit=z.infer<typeof sampleVisitSchema>;
export type DemoState=z.infer<typeof demoStateSchema>;
export const stageLabels={draft:'Draft',review:'Decision to review',waiting:'Waiting for sample reply',plan:'Sample plan ready',declined:'Alternative declined',cancelled:'Cancelled'};
export function initialDemo():DemoState{return {needs:['A step-free route all the way to the room','A place to sit and rest','Advance notice of loud sound'],visits:[
 {id:'studio',title:'Clay, coffee & company',venue:'Willow Clay Studio',category:'Class',date:'Saturday, 19 September · 11:00',needs:['Step-free access to the classroom','A seated place at the workbench','A quieter arrival time'],issue:'The entrance is step-free, but the booked classroom is upstairs and the lift is unavailable.',proposal:'Ask to join the same class in the ground-floor studio, at the same time. Keep the step-free requirement unchanged.',website:'Our main entrance is step-free. Classes take place in both of our studios.',reply:'Your class is currently in the upstairs studio. The lift is out of service. We may be able to move your session to the ground floor.',resolution:'We can run the 11:00 class in the ground-floor studio. There are no steps from the main entrance to that room, and we have a seated workbench available.',arrival:'Use the main entrance and ask for the ground-floor studio. The sample reply confirms the route and a seated workbench. A quieter arrival time is still unconfirmed.',stage:'review',paused:false,shared:[true,true,false],history:['Sample venue reply received','Room access conflict identified']},
 {id:'dining',title:'Dinner with friends',venue:'Cedar Table',category:'Dining',date:'Friday, 25 September · 18:30',needs:['A table away from speakers','A step-free route to the table','Space for a rest before the meal'],issue:'The restaurant mentions a quieter corner, but live music starts at 19:00. The booked time overlaps.',proposal:'Ask about an earlier table at 17:30, away from the speakers. Confirm the route to that specific table before changing the plan.',website:'Our courtyard has a quieter seating area. Friday evenings feature live music.',reply:'Music starts at 19:00 and reaches the courtyard. An earlier table may work, but please tell us which arrival time you would prefer.',resolution:'Our sample earlier table at 17:30 is away from the speakers. The route from the front entrance is step-free. Music still starts at 19:00, so a longer stay would overlap.',arrival:'The proposed sample arrival is 17:30, through the front entrance. Music starts at 19:00. A rest space before the meal has not been confirmed.',stage:'review',paused:false,shared:[true,true,false],history:['Sample music schedule checked','Arrival-time decision prepared']},
 {id:'gallery',title:'An afternoon with art',venue:'Northlight Gallery',category:'Culture',date:'Sunday, 27 September · 14:00',needs:['Seating through the exhibition route','A step-free route to the exhibition','A quiet place near the exit'],issue:'The original website only mentions seating in the lobby, leaving the exhibition route unclear.',proposal:'Ask about seats in each exhibition room and the full route from entrance to exhibition.',website:'Seats are available in the lobby. The gallery entrance is step-free.',reply:'We can provide chairs in both exhibition rooms. The exhibition and lobby are on the same level.',resolution:'Our sample reply confirms chairs in both exhibition rooms and a step-free route from the entrance. A separate quiet space near the exit has not been confirmed.',arrival:'Enter through the main doors and ask for exhibition rooms one and two. Sample evidence covers the route and seating; the quieter exit space remains unknown.',stage:'plan',paused:false,shared:[true,true,false],history:['Sample room-by-room reply received','Sample plan prepared with one open preference']}
 ]};}
export type DemoAction='approve'|'reply'|'decline'|'pause'|'resume'|'cancel'|'reopen'|'check';
export function updateSample(visit:SampleVisit,action:DemoAction):SampleVisit{
 if(visit.stage==='cancelled')return visit;
 if(visit.paused&&!['resume','cancel'].includes(action))return visit;
 const withEvent=(patch:Partial<SampleVisit>,event:string)=>({...visit,...patch,history:[event,...visit.history].slice(0,100)});
 if(action==='pause')return withEvent({paused:true},'You paused this sample arrangement');
 if(action==='resume')return withEvent({paused:false},'You resumed this sample arrangement');
 if(action==='cancel')return withEvent({stage:'cancelled',paused:false,shared:visit.shared.map(()=>false)},'You cancelled; sample sharing permission revoked');
 if(action==='approve'&&visit.stage==='review'&&visit.shared.slice(0,Math.min(2,visit.needs.length)).every(Boolean))return withEvent({stage:'waiting'},'You approved the sample question; simulated message prepared');
 if(action==='reply'&&visit.stage==='waiting'&&!visit.id.startsWith('sample-'))return withEvent({stage:'plan'},'You loaded a fictional venue reply; sample plan updated');
 if(action==='decline'&&visit.stage==='review')return withEvent({stage:'declined'},'You declined the alternative; original requirements retained');
 if(action==='reopen'&&visit.stage==='declined')return withEvent({stage:'review'},'You reopened the sample proposal for review');
 if(action==='check'&&visit.stage==='draft')return withEvent({stage:'review'},'Sample question review opened; no research performed');
 return visit;
}
